---
# <gt> creates a new task line. <gg> set completion timestamp on current
# - name: Configure vim for working with todo files
#  blockinfile:
#    path: ~/.vimrc
#    marker: '" {mark} ANSIBLE MANAGED BLOCK'
#    block: |
#      " check off a todo item and time stamp it
#      map gg ^rx: <Esc>:r! date +" [\%H:\%M]"<ENTER>kJA<Esc>$
#      " create a new todo item
#      map gt o  _


- name: Ensure configured homebrew packages are installed.
  homebrew:
    name: "todo-txt"
    state: present

- name: check if ~/Nextcloud exsists
  stat:
    path: ~/Nextcloud
  register: nextcloud_folder

- name: Configure todo-txt config file
  blockinfile:
    path: ~/.todo/config
    block: |
      export TODO_DIR="$HOME/Nextcloud"
      export TODO_FILE="$TODO_DIR/todo.txt"
      export DONE_FILE="$TODO_DIR/done.txt"
      export REPORT_FILE="$TODO_DIR/report.txt"
      export TMP_FILE="/tmp/todo.tmp"
      export TODOTXT_DEFAULT_ACTION=ls
  when: nextcloud_folder.stat.exists == True

- name: Configure bash aliases for working with todos
  blockinfile:
    path: ~/.bash_aliases
    block: |
      alias ea='vi $HOME/.bash_aliases; source $HOME/.bash_aliases && echo "$HOME/.bash_aliases sourced  --ok."'
      # configure todo.sh as alias t and assign bash autocompletion to the alias t
      alias t='todo.sh'
      complete -F _todo t

- name: Include configure_vim.yml
  include: configure_vim.yml
